name: PR Build
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn
            - name: Build
              run: yarn build
            - run: yarn
              working-directory: ./create
            - name: Build
              run: yarn build
              working-directory: ./create
